apiVersion: v1
kind: Service
metadata:
  name: techops-jenkins
  namespace: techops-jenkins
  labels:
    app: jenkins
    team: techops
    env: qa
spec:
  ports:
    - name: jenkins-webui
      port: 8080
      targetPort: 8080
    - name: jenkins-api
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins
    team: techops
    env: qa
  type: LoadBalancer
