apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tls-example
  namespace: techops
  labels:
    app: nginx-tls-example
spec:
  selector:
    matchLabels:
      app: nginx-tls-example
  replicas: 2
  template:
    metadata:
      namespace: techops
      labels:
        app: nginx-tls-example
    spec:
      containers:
      - name: nginx-tls-example
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tls-example
  namespace: techops
  labels:
    app: nginx-tls-example
spec:
  type: LoadBalancer
  selector:
    app: nginx-tls-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
